---
vsphere_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32663835316264386638666661643933313238383065326264366539633833306131303537313838
          6264393034323432353338386438316438623561616233340a656131663930663034366237363431
          32343063643663633366626364363961666463343261366236373238386562633637333064333135
          3165376437313134660a646635613662343934313638373031616466346634343037346263633239
          35343738303039633861613266333161363538373037353938663132653934646235

vsphere_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61633533616339323531333633313636383662656262656562323665613432363434383634616233
          3836613966333936303536323866323532633637343837300a363264306666656138323932666431
          32303264306435336431663262336465646263353437303537623866333632646530666363633563
          6234376232383933330a306163646666363133373264613230316238376532326235613835616631
          37633366643262323635663732323436333037316632636438656261393931333965

vsphere_server: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37626265393236363062383830353861396539626232363762363365373965313862633039656133
          3336393938633437313962353038643938313034613730620a633534386334613131326565353161
          38336236643339366563613434366561333262303561643831343139383439313833623138653562
          3963663561376636650a306433646161633338303365623061323962303761316230353365343337
          33643162646365386337663238313562633234366136653463646231313065663430

vsphere_cluster: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36653831386532316363323035313339373731313739613466616233346138643962343564353466
          6562643931303266653031396633623164306262666362330a383134653037643564363034626137
          38353636656637656564376237316430333161303631616636666665633066323332393933376230
          6430373566383433650a616666326634653138653839383530643532306134623763653464383834
          6231

vsphere_datacenter: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61366531373739613038303136303863393962636133373030646463323736666337636539393364
          3638356532383661633638333431623436626466353937610a623636313462633135653162303034
          39396165363666323139643334653034663434623239663034363438653266373563303938306165
          6132366663363761330a336362643365323134313337306262333635363034343762623130653065
          3833

vsphere_datastore: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31333934373437653338343036646439666439373637303763353566346132663430316237393132
          3539396662636161623830623461653635333965393634660a363230373062626338336330366330
          64383137333836313638303263333233383731356165313365393833343963323030653062316430
          3466383164376239360a633338376664333064366633313338386536313563306663613130376435
          31346665326466346436343030636164623664633236346163613638353837323732

vsphere_folder: ansible_vms
